### ISSUE TITLE
프로젝트 환경 세팅

### ISSUE THREAD

**Issue by giseoplee** [mint-rare/plan#1]
### 이슈 내용
- 각 모듈 별 프로젝트 환경 세팅을 진행합니다.
- [x] frontend
- [x] backend
- [x] contract

### 작업 대상 모듈
`backend`
`frontend`
`contract`

**Comment by giseoplee** [comment]
@airfluid님, 코멘트 감사합니다!

contract는 트러플, 가나슈로 환경 구성 진행 해보겠습니다 :)
https://github.com/klaytn/klaytn-contracts
현재 위 내용 기반으로 버전을 올려가면서 테스트 중에 있습니다.
초안 잡히면 리뷰 한번만 부탁 드릴게요!

---

지금 frontend랑 맞춰서 진행하고 싶은 부분이 있어서 틀을 잡아보고 있는데요!
병렬로 진행해도 이슈 없을 것 같습니다~

**Comment by airfluid** [comment]
@giseoplee 답변 감사드립니다 👍 
그리고 유명한 프로젝트인 'decentraland' 코드가 전부 공개이더군요. 마켓앱도 공개되어있으니 참고하셔도 좋을 것 같습니다.
> https://github.com/decentraland/marketplace

문제는 graph node 라는 이더리움 쪽 생태계에서 graphql로 정보를 조회가능하게 하는 라이브러리가 들어가있어서 api 호출 쪽은 크게 참고할 수 없을 것 같긴하네요.
