### ISSUE TITLE
로그인된 지갑에서 보유하고 있는 NFT 목록 조회 API 추가

### ISSUE THREAD

**Issue by giseoplee** [mint-rare/plan#10]
### 이슈 내용
- 로그인된 지갑이 보유하고 있는 NFT 목록을 조회할 수 있는 api를 추가합니다.
- https://refs.klaytnapi.com/ko/tokenhistory/latest#operation/getListOfTokenByOwnerAddress

### 작업 대상 모듈
(작업 대상 모듈만 남기고 지워주시면 됩니다.)
`backend`

**Comment by giseoplee** [comment]
@airfluid님, 현재 로그인된 지갑의 NFT를 민트레어 마켓에 등록하는 과정에서 스토리지가 필요하지 않을까 싶은데요..
제가 구상한 플로우는 아래와 같습니다.

1. 내가 보유한 NFT를 마켓에 등록하기 시작
2. 판매할 KLAY 입력 후 등록 완료 시 스토리지에 해당 데이터를 저장
3. 마켓에서 NFT list를 가져올 때 2에서 스토리지에 저장했던 NFT 목록을 우선순위로 출력 (판매 KLAY 내용 포함)

의견 부탁 드리겠습니다!

**Comment by airfluid** [comment]
@giseoplee 저도 db에 저장하는게 좋다고 생각이 들기 시작했습니다!.. 다른 메타 데이터도 저장할 수 있고, 어차피 저희 마켓에 등록된 서비스만 노출하게 되니까요.

**Comment by airfluid** [comment]
@giseoplee님, 저희 마켓에서 보여지는 상품들은 전부 저희 마켓 컨트랙트에 등록된 상품들인가요?? 

저는 검색 등의 쿼리 기능을 제공하기 위해서 경매 모델을 하나 만들고 그외에는 kas 를 이용해서 처리하려고 생각중이었습니다. 

그런데 웹을 통해서 자체 db에 저장한다 치면 걱정이 되는게 사용자가 직접 저희 마켓 컨트랙트를 이용해서 상품을 올릴때 처리가 걱정이 되는 부분이네요. (아직 잘 모르겠지만 컨트랙트 이벤트를 이용해 상품거래가 일어날때마다 db 작업을 하는 식으로 해도 될 것 같긴 하네요.)

**Comment by giseoplee** [comment]
@airfluid님, 마켓에서 보여지는 NFT 목록은 마켓에 판매 등록된 NFT 목록 + 화이트 리스트 처리된 발행처 내 NFT 목록으로 생각하고 있었습니다!

#### 마켓 판매 NFT 노출 플로우 (가정 : 한번에 노출될 NFT 카드 목록이 20개일 때)
1. 마켓 DB에 저장된 정보로 리스트 호출 (Ex. 13개 - 이 13개의 NFT는 가격 정보가 FE에 표기)
2. 20개 이하이기 때문에 화이트리스트 중 특정 컨트랙트의 NFT 목록을 7개 호출 (7개의 화이트 리스트 NFT는 FE에 가격 정보가 표기 X)
3. 하단 특정 스크롤 위치까지 스크롤이 도착했을 때 다음 20개의 NFT 목록을 화이트 리스트 NFT에서 호출

#### 마켓에 나의 NFT 등록 플로우
1. 마이 페이지 접근 -> 나의 NFT 카드 목록 중 매대에 업로드 할 NFT 카드 클릭
2. 가격, 노출 기간 설정
3. 해당 정보와 NFT 판매 관련 정보를 DB에 저장
4. 마켓 컨트랙트에서 해당 NFT를 전송할 수 있는 권한 획득? (이 부분은 조금 더 확인이 필요할 것 같습니다.)
    - 구매자가 구매 시 해당 NFT를 구매자에게 할당, 판매자에게는 구매자에게 KLAY를 할당 필요
    - 구매자, 판매자에게 토큰 할당 필요

---

> 그런데 웹을 통해서 자체 db에 저장한다 치면 걱정이 되는게 사용자가 직접 저희 마켓 컨트랙트를 이용해서 상품을 올릴때 처리가 걱정이 되는 부분이네요. (아직 잘 모르겠지만 컨트랙트 이벤트를 이용해 상품거래가 일어날때마다 db 작업을 하는 식으로 해도 될 것 같긴 하네요.)

이 부분 코멘트만으로는 이해가 어려운데요.
조금 상세히 풀어서 설명 부탁드려도 될까요?

**Comment by airfluid** [comment]
@giseoplee 

 **마켓 컨트랙트 내부에는 등록된 상품의 정보를 가져오는 메서드가 존재합니다.** 
이를 통해서 블록체인 상에서의 정보를 읽어 올 수 있기 때문에 제가 처음에 db가 필요할까라는 의견을 제시한거였고, 지금에 와서는 정렬이나 검색 등의 쿼리를 쉽게 적용하기 위해서 별도의 db가 필요하겠다라는 생각을 하게되었습니다.

 **컨트랙트 코드가 블록체인 상에 올라가기 때문에 굳이 웹이 아니더라도 사용자는 저희 마켓에 NFT를 등록할 수 있습니다.**
이렇게 되면 위에서 말했듯이 웹에서 사용자들에 의해 변하는 저희 DB와는 다른 정보를 가질 수 있게 되고, 이는 실제 블록체인상의 정보와 저희의 DB상의 정보가 일치하지 않게되는 것을 의미합니다.

 **이때 서버상에서 컨트랙트의 이벤트를 구독하면 동기화시킬 수 있지 않을까라는 생각을 했습니다.**
contract 내에 이벤트를 만들고 (예를 들면 `UserNftSold`와 같이 판매가 되면 실행되는 이벤트) 이를 backend 단에서 구독하여 물건의 거래 정보를 db상에 기록하는 것 입니다. 이렇게 되면 블록체인 상의 저희 market contract의 상태와 db 상태가 일치하게 될꺼라고 기대할 수 있습니다.

---

### 요약
제 의견을 드리자면,

1.  db는 사용자 경험을 높이기 위한 수단으로 NFT와 거래 정보를 저장해야 함. (사실 이 모든 정보는 컨트랙트로 접근 가능)
2. 자체 db와 컨트랙트 상의 동기화를 위해 컨트랙트의 event 라는 개념을 도입. (사실 이게 잘 될지는 저도 모르겠습니다.)

**Comment by giseoplee** [comment]
@airfluid님, 케이스 공유 감사합니다.
이 부분은 고려가 되는게 좋을거 같기도 하네요!
