### ISSUE TITLE
마켓에 리스팅될 NFT 목록 조회 API 추가

### ISSUE THREAD

**Issue by giseoplee** [mint-rare/plan#11]
### 이슈 내용
- 마켓에 리스팅될 NFT 목록을 조회합니다.
- https://refs.klaytnapi.com/ko/tokenhistory/latest#operation/getNftsByContractAddress

### 작업 대상 모듈
`backend`

**Comment by zioznjeje** [comment]
@giseoplee 
네- 확인하였습니다! 감사합니다 :)
