### ISSUE TITLE
데이터베이스 초기설정

### ISSUE THREAD

**Issue by airfluid** [mint-rare/plan#12]
### Collections : 프로젝트 단위 (e.g. Doge Sound Club, 인절미, 메타콩즈)
- address: 주소
- name: 컬렉션 이름 (프로젝트 이름)

### Asset : NFT 단위
- tokenId: 토큰 번호 (nft 별 고유 번호)
- meta: 메타데이터
- contract: Collection 오브젝트 아이디
- owner: 소유자 정보
- price: 가격 정보

### Activity
- action: 작업 종류 (Offer, Listing, Buy 등)
- image: 이미지 주소
- name: nft 이름
- price: 가격
- from: 주소 (nft 이동)
- to: 주소 (nft 이동)

**Comment by giseoplee** [comment]
https://github.com/mint-rare/plan/issues/4#issuecomment-1037253991
오늘 마일스톤 리뷰에서 위 기능명세서를 리뷰 후, 
확정되는 스펙에 따라 데이터 규격에도 변경이 필요할 수 있을 것 같습니다!

**Comment by airfluid** [comment]
@giseoplee mongodb 사용 고려하여 카멜케이스로 수정하였습니다.!
