### ISSUE TITLE
서비스 인프라 구축

### ISSUE THREAD

**Issue by giseoplee** [mint-rare/plan#13]
### 이슈 내용
- EC2 free tier 인스턴스를 발급받아 아래와 같은 인프라를 구축합니다.
- Storage는 MongoDB로 결정되었습니다.
![152687619-dcb9c2b0-e03b-4651-806f-e45d6b5c4bea](https://user-images.githubusercontent.com/10542986/153747998-6363697d-a6e8-4c39-89be-232ebdde64b5.png)

(cc. @airfluid @zioznjeje)

### 작업 대상 모듈
(작업 대상 모듈만 남기고 지워주시면 됩니다.)
`backend`
`frontend`

**Comment by giseoplee** [comment]
@airfluid님, EC2 몽고디비 접근 정보 참고 부탁 드립니다.
- https://github.com/mint-rare/secrets/issues/1

**Comment by airfluid** [comment]
@giseoplee DB도 따로 인스턴스 하나로 돌리시는건가요?
저는 일단 로컬에서 작업하다가 docker-compose 로 db랑 node 서버 둘다 돌아가게 작업을 해둘 생각이었어서..
혹시 인프라부터 잡고 가는 이유가 있을까요?

**Comment by giseoplee** [comment]
@airfluid님, 1개 인스턴스에 서비스에 사용되는 프로세스를 모두 올리는걸로 구상하고 있었습니다.
근데 db를 docker로 쓰는 이유가 있으실까요?
영속성 이슈는 어떤 식으로 처리하실 예정이신지 정환님이 구상하신 내용을 공유주시면 감사할 것 같습니다!

인프라부터 잡고 간다기 보다는.. 
로컬이랑 별개 작업 후 나중에 싱크 맞추는 것보다 바로 개발서버에 붙어서 하는게 효율적일 것 같아서 DB 먼저 설치 후 공유 드렸습니다.

**Comment by airfluid** [comment]
@giseoplee 저는 volumes 설정으로 영속성 문제를 해결하고 컴포즈 파일 하나로 배포하는게 간단한 프로젝트에서는 좋다고 생각해서요. 이야기 듣다보니 기섭님 방식이 좋은 것 같으니 따라가겠습니다!!

**Comment by giseoplee** [comment]
@airfluid님, 의견 수렴 감사합니다! 🙏
host os랑 종속성이 있는 DB만 ec2에 바로 올려서 사용하는걸로 하고 독립성이 있는 nest는 docker로 말아주셔도 될 것 같습니다!

**Comment by giseoplee** [comment]
#### 인프라 구성 최종

![mingrare-infra](https://user-images.githubusercontent.com/10542986/155698879-181661a7-bfd6-4c44-a1dc-6e096623840b.png)
