### ISSUE TITLE
node, npm 버전

### ISSUE THREAD

**Issue by giseoplee** [mint-rare/plan#14]
### 이슈 내용
이걸 놓치고 있었네요;
지금 각자 작업 환경의 node, npm 버전이 어떻게 되실까요?
저는 node 14.16.1 / npm 7.23.0로 사용하고 있습니다.

ec2 인스턴스에 설치할 버전은 크러시 안나는 버전으로 맞춰야 할 것 같네요.

@airfluid님, @zioznjeje님, 확인 부탁 드리겠습니다!

### 작업 대상 모듈
`backend`
`frontend`

**Comment by zioznjeje** [comment]
@giseoplee 
저는 node v16.13.0 / npm v8.1.0 사용하고 있습니다~

**Comment by airfluid** [comment]
caver-js 호환성을 위해서 노드는 14 버전대로 고정해야할 것 같으니 확인해보고 바로 올리겠습니다.

**Comment by giseoplee** [comment]
@zioznjeje님, 로컬에서 frontend repo 이슈 없이 돌아가나요?
아래 내용을 봤을 때 16은 아직 지원 전인거 같아 보여서요! (@airfluid님 공유 감사합니다!)
https://github.com/klaytn/caver-js#requirements

**Comment by zioznjeje** [comment]
@giseoplee (cc. @airfluid)
우선 제 레포에도 14 버전대로 고정해두었습니다~!

**Comment by zioznjeje** [comment]
넵!
