### ISSUE TITLE
중간 점검 피드백 받고 싶은 내용 정리

### ISSUE THREAD

**Issue by giseoplee** [mint-rare/plan#15]
### 이슈 내용
- 중간 점검 피드백 받고 싶은 내용을 코멘트로 작성해주시면 됩니다!
- @netgamer님, 내용을 취합하여 중간점검 pptx에 포함 부탁 드리겠습니다! 🙇 

### 작업 대상 모듈
`service`

**Comment by netgamer** [comment]
해커톤 Team14의 채택된 아이디어를 쓴 오세준님이 개인적인 사정으로 팀을 하차 하였기에 
팀원들끼리 급하게 회의를 소집하여 현재 가능한 아이디어를 취합. 룩스레어의 클론 프로젝트로 민트레어가 나오게 되었습니다
늦게 시작한 프로젝트인 만큼 아이디어를 정리하고 기획문서가 늦게 나온점을 감안하여 
중간 점검 피드백이지만 기능적인 부분보다는 해당프로젝트의 기획 및 방향성에 대한 부분을 체크해주셨으면 합니다

**Comment by netgamer** [comment]
[2022 02 13 17:00] 0.1.0 마일스톤 리뷰
https://github.com/mint-rare/plan/wiki/%5B2022-02-13-17:00%5D-0.1.0-%EB%A7%88%EC%9D%BC%EC%8A%A4%ED%86%A4-%EB%A6%AC%EB%B7%B0

개발환경 구축에 대한 내용을 주로 회의 하였으며 4명이 frontend, backend, contract, service으로 나누어 작업을 진행중이며 
디자인부분은 외부 지인을 통해서 로고작업등을 진행하였습니다.
시간이 촉박하기 때문에 완벽한 UI보다는 민트레어의 특징 기능적인 부분을 고려하여 진행하고 있습니다

카이카스 지갑로그인 구현 > 
nft목록 구현 > 
nft목록에서 sell 클릭시 리스팅 구현 > nft구매 구현 > 
looks토큰 발행 > 
nft구매시 looks리워드 지급 구현
