### ISSUE TITLE
기능명세 확정

### ISSUE THREAD

**Issue by giseoplee** [mint-rare/plan#2]
### 이슈 내용
- 해커톤에서 구현할 기능 명세를 확정합니다.
- 웹 페이지 별로 기능 명세를 정의합니다.
- 코멘트로 각 모듈 별 기능 상세 명세를 정의합니다.

## 홈
- 서비스 소개 노출

## 마켓
- 화이트리스트 NFT 목록 카드 리스트뷰로 노출
- 사이드 바

## 마이 페이지
- 보유 NFT 목록 노출

### 작업 대상 모듈
`service`

**Comment by giseoplee** [comment]
## Frontend
- [ ] 클립, 카이카스 지갑 연동
- [ ] 화이트 리스트된 NFT 목록 리스트 뷰 구현

**Comment by giseoplee** [comment]
## Backend
- [ ] DB 설계
  - 오퍼, 오퍼 알림 등은 컨트랙트가 아닌 별로 DB로 관리해야 하지 않을까 싶네요?!

**Comment by giseoplee** [comment]
## Contract
- [ ] NFT 구매
- [ ] 나의 NFT를 판매 목록에 리스트업

**Comment by giseoplee** [comment]
## 인프라
- [ ] EC2 free tier 발급
- [ ] DB 설치
- [ ] 필요에 따라 메모리 DB 설치
- [ ] Nginx 설치 및 설정

**Comment by airfluid** [comment]
> ## Backend
> * [ ]  DB 설계
>   
>   * 오퍼, 오퍼 알림 등은 컨트랙트가 아닌 별로 DB로 관리해야 하지 않을까 싶네요?!

@giseoplee  
오퍼 알림이 뭘 의미하는건지 알 수 있을까요? 
팔렸다 이런 정보를 사용자단에게 알려주는 걸 말씀하시는거면 그것도 스마트 컨트랙트 내에서 구현이 가능한 것으로 알고 있습니다.

**Comment by giseoplee** [comment]
@airfluid님, 공유 감사합니다!

https://opensea.io/assets/0x4db1f25d3d98600140dfc18deb7515be5bd293af/2062

위의 NFT 기준을 예시로 들었을 때 아래 기능입니다!

![스크린샷 2022-02-07 오후 8 31 33](https://user-images.githubusercontent.com/10542986/152780282-1669df64-478e-4640-b7dd-f8b669073e2f.png)

아래와 같은 규격으로 통신하는 것으로 확인되는데요..
규격을 보고 offer 데이터 자체는 DB로 관리되는게 아닌가 싶어서요!

알람의 경우는 말씀해주신 event를 쓰면 되겠네요 공유 감사합니다 :)

### request
![스크린샷 2022-02-07 오후 8 35 50](https://user-images.githubusercontent.com/10542986/152780872-4676d3bd-2e83-431e-b0a4-ebfaf5469793.png)

### response
![스크린샷 2022-02-07 오후 8 35 25](https://user-images.githubusercontent.com/10542986/152780809-2ddf7c7a-b89a-41c0-a725-5926c55364b4.png)

---

네넵 DB 도입 여부는 정환님이 결정해주시면 될 것 같아요!

**Comment by giseoplee** [comment]
https://github.com/mint-rare/plan/issues/4#issuecomment-1039107753
