### ISSUE TITLE
Market List 페이지 - API 연동

### ISSUE THREAD

**Issue by zioznjeje** [mint-rare/plan#22]
### 이슈 내용
(이슈 내용을 작성합니다.)
* Market List 페이지에 필요한 API를 연동합니다.

<작업 내용>
- [x] Market List 페이지에서 내부의 token list api를 호출합니다.

### 작업 대상 모듈
(작업 대상 모듈만 남기고 지워주시면 됩니다.)
`backend`
`frontend`

**Comment by airfluid** [comment]
### Token List API
- 처음 호출 시 `GET /api/assets?limit={Front에서 조절}`
- 페이지네이션 `GET /api/assets?limit={Front에서 조절}&cursor={cursor}`
