### ISSUE TITLE
My Page - API 연동

### ISSUE THREAD

**Issue by zioznjeje** [mint-rare/plan#24]
### 이슈 내용
(이슈 내용을 작성합니다.)
* My Page에 필요한 API를 연동합니다.

<작업 내용>
- [x] My Page에서 내부의 user collected list api를 호출합니다.
- [x] 민트레어 토큰 노출 기능 추가
- [x] 판매모달 추가
- [x] Contract 판매 API 연동

### 작업 대상 모듈
(작업 대상 모듈만 남기고 지워주시면 됩니다.)
`backend`
`frontend`

**Comment by zioznjeje** [comment]
@giseoplee 
네 맞습니다! 빠져있어서 함께 추가하려고 합니다!
> 해당 토큰은 저희 api말고 contract api 찌르면 되지요? 👀

**Comment by airfluid** [comment]
@zioznjeje 님, 마이 페이지 뷰에서도 Infinity Scroll 방식을 적용하실 예정이신가요?
API 작성하다가 그 부분은 미쳐 생각하질 못한거 같습니다 😅
일단 소유하고 있는 nft인 owned를 페이지네이션 할 수 있게 짜두겠습니다.

**Comment by airfluid** [comment]
### 유저가 보유중인 NFT 페이지네이션
- `GET /api/user/:address/assets?cursor={}&limit={}`

```json
{
	"data": {
		"tokens": [
			{
				"contract": {
					"address": "0xe47e90c58f8336a2f24bcd9bcb530e2e02e1e8ae"
				},
				"tokenId": 3973,
				"meta": {
					"name": "DSC Mate #3973",
					"description": "클레이튼 체인 최초의 제너레이티브 아트, 도지사운드클럽의 투표권으로 사용됨.",
					"image": "https://storage.googleapis.com/dsc-mate/336/dscMate-3973.png",
					"background_color": "#F6D613",
					"sendable": true,
					"attributes": [
						{
							"trait_type": "Level",
							"value": 6,
							"max_value": 11
						},
						{
							"trait_type": "Face",
							"value": "Female"
						},
						{
							"trait_type": "Face Detail A",
							"value": "Orange Stripes"
						},
						{
							"trait_type": "Eyes",
							"value": "Normal Glasses"
						},
						{
							"trait_type": "Headwear",
							"value": "Bucket Hat"
						},
						{
							"trait_type": "Headwear Detail",
							"value": "Goggle on forehead"
						},
						{
							"trait_type": "Ears",
							"value": "Gold Earring"
						},
						{
							"trait_type": "Items",
							"value": "Normal Gas Mask"
						}
					],
					"external_url": "https://dogesound.club/mates/3973"
				}
			},
			{
				"contract": {
					"address": "0xe47e90c58f8336a2f24bcd9bcb530e2e02e1e8ae"
				},
				"tokenId": 3924,
				"meta": {
					"name": "DSC Mate #3924",
					"description": "클레이튼 체인 최초의 제너레이티브 아트, 도지사운드클럽의 투표권으로 사용됨.",
					"image": "https://storage.googleapis.com/dsc-mate/336/dscMate-3924.png",
					"background_color": "#F6D613",
					"sendable": true,
					"attributes": [
						{
							"trait_type": "Level",
							"value": 4,
							"max_value": 11
						},
						{
							"trait_type": "Face",
							"value": "Rabbit"
						},
						{
							"trait_type": "Neck",
							"value": "Red Scarf"
						},
						{
							"trait_type": "Eyes",
							"value": "Horned Rim Glasses"
						},
						{
							"trait_type": "Headwear",
							"value": "Not Arranged Green "
						},
						{
							"trait_type": "Items",
							"value": "LED Gas Mask"
						}
					],
					"external_url": "https://dogesound.club/mates/3924"
				}
			}
		],
		"cursor": "eNoAzq5E6Lwa7WYZMpbpELGg8dMPaWo0KNV2kqY74A0QVJXNodeqKp3BYG92aDy23RWP7bExZ8v1O5zl6MrmwLgkwQmOJex3rlZzB9A4DX16v5PlK10D29kVJX3bgmQ4"
	}
}
```

**Comment by zioznjeje** [comment]
@airfluid 
정환님~ 마이페이지 Owned List API에서 500 에러가 발생합니다.
제 주소가 정상적으로 연동 되었는데도, 아래와 같은 에러메세지가 뜨는데 확인 부탁드려요..! 😢 

* URL: GET `/api/user/0xb0cdebe5725c9141e94a77245f6ab330ada02b50/owned?cursor=&limit=20`
* Status: `500`
* Error (message): `The credential you provided does not match in our record.`

**Comment by zioznjeje** [comment]
@airfluid 
정환님~ 마이페이지 Owned List API에서 500 에러가 발생합니다.
제 주소가 정상적으로 연동 되었는데도, 아래와 같은 에러메세지가 뜨는데 확인 부탁드려요..! 😢 

* URL: GET `/api/user/0xb0cdebe5725c9141e94a77245f6ab330ada02b50/owned?cursor=&limit=20`
* Status: `500`
* Error (message): `The credential you provided does not match in our record.`

**Comment by zioznjeje** [comment]
@airfluid 
늦은 시각까지 대응해주셔서 감사합니다! 해당 json으로 변경 후 정상동작합니다! 🙏

**Comment by airfluid** [comment]
### 상품 등록 후 호출할 API
- `POST /user/:userAddress/listing`
- body 에는 address, tokenId 담아서 주시면 됩니다. (컨트랙트 주소와 토큰 아이디)

### 예시
- `POST /user/0x539b01978836fe7d1915a890e5efe1ae3f53f9a3/buy`
   - address: 0x9faccd9f9661dddec3971c1ee146516127c34fc1
   - tokenId: 1540796840
- 정상적으로 실행되면 success: true 와 asset 데이터를 보냅니다.
