### ISSUE TITLE
마켓 페이지 - 구매, 등록 성공시 API 호출

### ISSUE THREAD

**Issue by zioznjeje** [mint-rare/plan#27]
### 이슈 내용
(이슈 내용을 작성합니다.)

- [x] 구매 성공시 API를 호출합니다.
- [x] 판매 등록 성공시 API를 호출합니다.

### 작업 대상 모듈
(작업 대상 모듈만 남기고 지워주시면 됩니다.)
`backend`
`frontend`

**Comment by airfluid** [comment]
### 구매 완료 시 호출할 API
- `POST /user/:userAddress/buy`
   - body 에는 address, tokenId 담아서 주시면 됩니다. (컨트랙트 주소와 토큰 아이디)

### 예시
- `POST /user/0x539b01978836fe7d1915a890e5efe1ae3f53f9a3/buy`
   - address: 0x9faccd9f9661dddec3971c1ee146516127c34fc1
   - tokenId: 1540796840
