### ISSUE TITLE
상세 기능 명세를 위한 리서치

### ISSUE THREAD

**Issue by giseoplee** [mint-rare/plan#4]
### 이슈 내용
- 상세 기능 명세를 위해 벤치 마킹 대상인 서비스들의 기능을 리서치하여 정리합니다.
  - 정리된 기능 목록 중 개발 일정 내 가능할 것 같은 부분까지 해커톤 범위를 잡아보는게 어떨까 싶습니다!

#### 리서치 대상
- https://looksrare.org
  - 준호님 담당 (~ 2022-02-09)
- https://pala.world/square
  - 세준님 담당 (~ 2022-02-??)

@planmoon님, @netgamer님, 각각 하나씩 맡아서 리서치 부탁드려도 될까요?

(cc. @zioznjeje @airfluid)

### 작업 대상 모듈
`service`

**Comment by airfluid** [comment]
저희 gist에 의견에서도 느꼈지만, 

1. 어떤식으로 에어드랍을 할지에 대한 논의
2. 자체 발행된 토큰들의 활용법

이 두 가지는 따로 이슈로 남겨서 계속 얘기해볼 필요가 있을 것 갘네요. 제가 이해한 바로는 룩스레어가 오픈시의 유저층을 확보하기 위해 에어드랍을 그렇게 진행한 걸로 알고 있거든요. 

그리고 해당 유저들에 대한 정보를 어떤식으로 쿼리할지!
(약간의 리서치가 필요할 것 같습니다.)

**Comment by giseoplee** [comment]
@airfluid님, 전적으로 동의합니다!
해당 이슈 생성해두겠습니다!

2번 토큰 활용의 경우 참조할 수 있는 다른 서비스들의 레퍼런스가 꽤 있는..? 편인 것 같은데 
1번은 어떤 방법들이 있는 지, 기술적으로 어떻게 풀어야 할 지 감이 좀 안잡히네요.. 😓 

일단 저희 메인 기능인 NFT 마켓을 어느정도 완성 후,
분담해서 리서치 해보는게 좋을 것 같은데 어떻게 생각하시나요?

@mint-rare/all

**Comment by giseoplee** [comment]
### LookRare 리서치 및 기능 명세 초안 (by. 준호님)
- [MintRare기능명세+LooksRare리서치.pptx](https://github.com/mint-rare/plan/files/8025266/MintRare.%2BLooksRare.pptx)

**Comment by giseoplee** [comment]
### 민트레어 해커톤 목표 기능 명세서 초안 (2022-02-13)
- [기능명세서_2022_02_13.pdf](https://github.com/mint-rare/plan/files/8053785/_2022_02_13.pdf)

**Comment by giseoplee** [comment]
### 민트레어 해커톤 목표 기능 명세서 v0.2 (2022-02-13)
- [기능명세서_2022_02_13_v0.2.pdf](https://github.com/mint-rare/plan/files/8055267/_2022_02_13_v0.2.pdf)

### 변경 내용
- 비로그인 마이페이지 페이드 아웃
