### ISSUE TITLE
eslint, prettier 설정 변경

### ISSUE THREAD

**Issue by giseoplee** [mint-rare/plan#5]
### 이슈 내용
- eslint / prettier 설정을 협의 후 변경합니다.

### 작업 대상 모듈
(작업 대상 모듈만 남기고 지워주시면 됩니다.)
`backend`
`frontend`

**Comment by airfluid** [comment]
backend 는 nest 기본 세팅을 사용할 예정이니 프론트 협의만 되면 이슈 닫아도 될 듯 합니다.

**Comment by giseoplee** [comment]
@airfluid님, 아래 설정 유지에 이슈 없으시다는 걸까요?
#### backend
- eslint : https://github.com/mint-rare/backend/blob/develop/.eslintrc.js
- eslintignore : https://github.com/mint-rare/backend/blob/develop/.eslintignore
- prettier : https://github.com/mint-rare/backend/blob/develop/.prettierrc
- prettierignore : https://github.com/mint-rare/backend/blob/develop/.prettierignore

@zioznjeje님, frontend 설정 중 변경 희망하시는 부분이 있으실까요?

#### frontend
- eslint : https://github.com/mint-rare/frontend/blob/develop/.eslintrc
- eslintignore : https://github.com/mint-rare/frontend/blob/develop/.eslintignore
- prettier : https://github.com/mint-rare/frontend/blob/develop/.prettierrc
- prettierignore : https://github.com/mint-rare/frontend/blob/develop/.prettierignore

**Comment by zioznjeje** [comment]
@giseoplee 
개인마다 선호하시는 룰이 있으시겠지만, 
아래 eslint rule은 수정되면 좋을 것 같습니다.
```
// .eslintrc
{
  rules: {
     'react-hooks/exhaustive-deps': 'warn',
  }
}
```

prettier 같은 경우는 기호의 차이 같아서 반영되지 않더라도 크게 상관은 없습니다.
```
// .prettierrc
{
  tabWidth: 2,
  semi: true,
  jsxSingleQuote: true,
  jsxBracketSameLine: false,
  quoteProps: 'as-needed',
}
```

**Comment by zioznjeje** [comment]
물론 해당 rule을 강제화 시키면 부실 데이터 참조가 되지 않는 효과는 누릴 수 있겠지만, 
때때로는 초기 마운트시에만 실행하고자, 종속성을 무시하는 경우도 있습니다. ([React 공식문서에서도 Warning 정도로 취급하기도 하고요](https://ko.reactjs.org/docs/hooks-rules.html))
물론 권장하는 방법은 아니지만, 생각 외로 개발할때- 종속성을 무시하는 케이스도 있어서 저 같은 경우는 Warn 정도로 걸어두곤 합니다.

**Comment by giseoplee** [comment]
@zioznjeje님, 내용 공유 감사합니다!

예은님이 메인테이너이시니 예은님이 작업하기 편하신 룰로 가는게 좋을 것 같습니다!
수정 PR은 정환님까지 확인되시면 한번에 올리도록 하겠습니다!

**Comment by airfluid** [comment]
저도 오늘 작업중에 tabWidth 만 2칸으로 수정하여 작업 중이었습니다. 그 외에 수정 사항은 없어도 될 듯 합니다. 설정 공유 감사드립니다.

**Comment by giseoplee** [comment]
@airfluid님, backend와 frontend의 룰은 맞추는게 좋지 않을까 싶어서 질문을 드린거였는데요..
그럼 backend는 아래 내용에 대해 frontend와 별도로 가는걸로 할까요?
```
semi: true,
quoteProps: 'as-needed'
```

**Comment by airfluid** [comment]
@giseoplee 아하. 똑같이 적용하겠습니다

**Comment by giseoplee** [comment]
@zioznjeje님, 일단 작업이 급하니 작업 환경은 각 작업자가 편한대로 가는게 좋을 것 같습니다!
@airfluid님은 이미 변경 후 작업 중이시라고 공유주셔서 이따가 FE만 변경 PR 올릴게요!

**Comment by zioznjeje** [comment]
@giseoplee 
네넵! 확인 감사합니다-!
